Repository intra2net/guibot, pull requests merged in 2024-12, with the labels that each got.

#62 Move static attributes from GlobalConfig to controller params
  docs/examples/custom_controller.py
  guibot/config.py
  guibot/controller.py
  guibot/region.py
Labels: good first issue

#63 Enable image logging also for display controllers
  guibot/config.py
  guibot/controller.py
  guibot/finder.py
  guibot/imagelogger.py
  guibot/location.py
  tests/test_controller.py
  tests/test_finder.py
  tests/test_imagelogger.py
Labels: enhancement

#64 Provide internal unfind method to emulate inverse find
  guibot/region.py
Labels: bug
